Remove applicability of tts:direction on <p>
w3c/ttml2 pull request #1214
Opened 2020-11-12 05:19 UTC by palemieux

Closes #1211 
Closes #1213 
Closes #1211 

The _paragraph embedding level_ is determined by the `ipd`, instead of being determined by `tts:direction` as applied to `p`. This is compatible with CSS since, in CSS, `direction` sets the _paragraph embedding level_ and the combination of `direction` and `writing-mode` maps to `tts:writingMode`.

The effect of `tts:unicodeBidi` on `p` is clarified to match CSS.

2020-11-12 06:45 UTC, tairt commented on spec/ttml2.xml
> +<p>The <loc href="#terms-inline-progression-direction">inline progression direction</loc> determined by the computed value of this property explicitly establishes the <emph>paragraph level</emph> as
```suggestion
<p>The <loc href="#terms-inline-progression-direction">inline progression direction</loc> determined by the computed value of this property explicitly establishes the <emph>paragraph level</emph> as specified by <bibref ref="uax9"/>, &sect;4.3, Higher Level Protocol <phrase role="strong">HL1</phrase>.</p>
```
It may be better to take out the part where the application of the paragraph level to the TTML `<p>` elements is mentioned. This keeps it in line with the original text from chapter [10.2.12](https://www.w3.org/TR/2018/REC-ttml2-20181108/#style-attribute-direction). Also as I undestand it the paragraph level is not directly tied to TTML markup but is applied in a later stage during UAX9 processing.

2020-11-12 06:45 UTC, tairt commented on spec/ttml2.xml
> +</note>
I wonder why this note is necessary because the application of `tts:unicodeBidi` to `<p>` was already deleted in a change above.

2020-11-12 06:45 UTC, tairt commented on spec/ttml2.xml
>  then a <loc href="#terms-presentation-processor">presentation processor</loc> must use the value <code>normal</code>.</p>
It may be good to say:
* that in the previous version `tts:direction` was also applicable to the `<p>` element,
* specifiying `tts:direction` on `<p>` may lead to different rendering results depending on implementation,
* it is considered to re-introduce the application of `tts:direction`  to `<p>` with a clear, determinisic rendering expectation in a later version.

2020-11-12 06:53 UTC, palemieux commented on spec/ttml2.xml
> +</note>
The intent was for tts:unicodeBidi to remain applicable to <p>

2020-11-12 08:04 UTC, tairt commented on spec/ttml2.xml
> +</note>
My conclusion from the previous discussions has been that `tts:unicodeBidi` is not applicable to `<p>` (even if `tts:direction` would still be applicable to `<p>`). 

In my previous comment, I have confused the removal of applicability of `tts:direction` to `<p>` with the removal of applicability of `tts:unicodeBidi` to `<p>`. As I see the latter has not been removed, but should.

2020-11-12 15:54 UTC, nigelmegitt reviewed
Notes to consider (partly for myself, but sharing them in case others have views):
* Should we change the semantic derivation for `tts:direction` to be CSS 3 Writing Modes?
* #1213 doesn't say to remove the applicability of `tts:direction` to `p`, but that's what this PR does.
* #1213 says to make `tts:direction` on `p` set the inline progression direction in addition to the paragraph embedding level, but this PR does not do that.
* #1212 says to remove the applicability of `tts:unicodeBidi` from `p`, but this PR does not do that.

At the moment, it looks to me, unless I've misunderstood, that the PR does not match the requested changes from the issues it is intended to close. I look forward to discussing.

2020-11-12 15:55 UTC, palemieux commented on spec/ttml2.xml
> +</note>
> My conclusion from the previous discussions has been that tts:unicodeBidi is not applicable to <p> (even if tts:direction would still be applicable to <p>).

Can you provide a link to that discussion?

2020-11-12 15:56 UTC, palemieux commented
> At the moment, it looks to me, unless I've misunderstood, that the PR does not match the requested changes from the issues it is intended to close. I look forward to discussing.

Yes, the PR attempts to find a middle ground to address the concerns with changing the semantics of `tts:direction` on `p` to influence the IPD.

2020-11-12 18:03 UTC, cconcolato commented
Following our discussion I found one example in our catalog that uses dir on p:
```
<p begin="10844167t" end="29195834t" region="bottom" tts:direction="rtl" tts:unicodeBidi="embed" xml:id="ID_57d7c57f-ef91-42fd-8f32-0d1f237b5131">
  <span style="span">- תוכן מקורי של NETFLIX -</span>
</p>
```
the region is defined as 
```
<region tts:backgroundColor="transparent" tts:displayAlign="after" tts:extent="80.000% 80.000%" tts:origin="10.000% 10.000%" tts:textAlign="center" xml:id="bottom"/>
```
writing-mode is not used at all in the document

2020-11-12 18:12 UTC, palemieux commented
> <p begin="10844167t" end="29195834t" region="bottom" tts:direction="rtl" tts:unicodeBidi="embed" xml:id="ID_57d7c57f-ef91-42fd-8f32-0d1f237b5131">

@cconcolato What is the expected rendering?

2020-11-12 18:29 UTC, palemieux commented on spec/ttml2.xml
>  then a <loc href="#terms-presentation-processor">presentation processor</loc> must use the value <code>normal</code>.</p>
See https://github.com/w3c/ttml2/pull/1214/commits/18e8bf0ca7552d4ccc9774670372bb87aaac012a

2020-11-12 18:30 UTC, palemieux commented on spec/ttml2.xml
> +<p>The <loc href="#terms-inline-progression-direction">inline progression direction</loc> determined by the computed value of this property explicitly establishes the <emph>paragraph level</emph> as
See https://github.com/w3c/ttml2/pull/1214/commits/18e8bf0ca7552d4ccc9774670372bb87aaac012a

2020-11-13 04:34 UTC, tairt commented on spec/ttml2.xml
> +<p>The <loc href="#terms-inline-progression-direction">inline progression direction</loc> determined by the computed value of this property explicitly establishes the <emph>paragraph level</emph> as
Looks good! Thanks!

2020-11-13 04:35 UTC, tairt commented on spec/ttml2.xml
>  then a <loc href="#terms-presentation-processor">presentation processor</loc> must use the value <code>normal</code>.</p>
Exactly. Very good wording. Thanks!

2020-11-13 04:59 UTC, tairt commented on spec/ttml2.xml
> +</note>
It follows the argumentation of @skynavga e.g. in the last part of his [comment](https://github.com/w3c/ttml2/issues/1211#issuecomment-705279511) from 2020-10-08 and at the beginning of the [TTWG discussion](https://github.com/w3c/ttml2/issues/1211#issuecomment-705696362)  on 2020-10-08. There was also an [issue](https://github.com/w3c/ttml2/issues/1212) opened where title indicates to remote application of unicodeBidi to p. There has been no final consensus on this question, but following the argumentation it make sense to remove the application to p. 

The question I have is also: What are the reasons to keep unicodeBidi when application of direction is removed? unicodeBidi depends on a direction counterpart...

A solution of the unicodeBidi question may be resolved in another PR. But I would then not mix it with this PR and therefore not add additional text to chapter 10.2.48.

2020-11-13 05:24 UTC, palemieux commented on spec/ttml2.xml
> +</note>
@tairt `tts:unicodeBidi` is no longer applicable to `p` per your comment above. I however think we should handle `tts:direction` and `tts:unicodeBidi` in the same PR, since, as you state above, they are intimately related.

2020-11-13 05:44 UTC, tairt commented on spec/ttml2.xml
> +</note>
@palemieux Yes, makes sense. Thanks for the edit. Looks good to me!

2020-11-13 05:45 UTC, tairt approved these changes

2020-11-19 04:39 UTC, skynavga requested changes

2020-11-19 04:39 UTC, skynavga commented on spec/ttml2.xml
> +<p>The <loc href="#terms-inline-progression-direction">inline progression direction</loc> determined by the computed value of this property explicitly establishes the <emph>paragraph level</emph> as
This language is semantically inconsistent with §10.2.12.1.

2020-11-19 04:39 UTC, skynavga commented on spec/ttml2.xml
> +<p>In earlier editions of this specification, the <att>tts:direction</att> property applied to the <code>p</code> element. This use is now <phrase role="deprecated">deprecated</phrase> in absence of
It is inappropriate to deprecate functionality that has been deployed since TTML1 1st edition without providing a mechanism for an author to explicitly declare which behavior is desired (either the pre-existing behavior or the newly proposed, non-backwards compatible behavior). In other words, this change should not be treated as a candidate for deprecation.

2020-11-19 04:39 UTC, skynavga commented on spec/ttml2.xml
> +<p>In earlier editions of this specification, the <att>tts:unicodeBidi</att> property applied to the <code>p</code> element. This use is now <phrase role="deprecated">deprecated</phrase> in absence o
See above comment about deprecation.

2020-11-19 04:42 UTC, skynavga commented
Re: https://github.com/w3c/ttml2/pull/1214#issue-519627186, please note that the abbreviation _ipr_ does not mean _inline progression direction_ in TTML, it means _inline progression dimension_; therefore, to avoid confusion, it is best to spell out _inline progression direction_.

2020-11-19 05:05 UTC, skynavga commented
@cconcolato Re: https://github.com/w3c/ttml2/pull/1214#issuecomment-726243664, I would expect the rendering to be such that the region is left-right, top-to-bottom, containing a horizontally center aligned paragraph that has its content effectively wrapped in a RLE/PDF Unicode Bidirectional Controls pair, which content consists of the text

```- תוכן מקורי של NETFLIX -```

The Bidi reordered text should appear as follows, and translates as "Original Content of NETFLIX".

```- NETFLIX תוכן מקורי של -```

2020-11-19 16:19 UTC, palemieux commented on spec/ttml2.xml
> +<p>The <loc href="#terms-inline-progression-direction">inline progression direction</loc> determined by the computed value of this property explicitly establishes the <emph>paragraph level</emph> as
What is the semantic inconsistence?

2020-11-19 16:43 UTC, closed without merging