Fix #1232 by clarifying the [resolve timing] procedure
w3c/ttml2 pull request #1233
Opened 2021-05-25 14:04 UTC by nigelmegitt

Fix #1232 by clarifying that the active time duration of the current document instance _is_ the root temporal extent, and adding an elaboration note about the permitted range of ISD time coordinates.

2021-05-25 15:35 UTC, palemieux requested changes

2021-05-25 15:35 UTC, palemieux commented on spec/ttml2.xml
> +of the current <loc href="#terms-document-instance">document instance</loc> into an ordered sequence
Adding `root temporal extent` here introduces more uncertainty than it resolves.

2021-05-25 15:35 UTC, palemieux commented on spec/ttml2.xml
> +</note>
What about simply stating _for any given time t is there always exactly one ISD where t falls within that ISD's interval_, as suggested at https://github.com/w3c/ttml2/issues/1232#issuecomment-841360458

2021-05-25 16:23 UTC, nigelmegitt commented on spec/ttml2.xml
> +of the current <loc href="#terms-document-instance">document instance</loc> into an ordered sequence
I think it clarifies the existing uncertainty. Previously we had an undefined term, "active time duration", now we have a defined term. If you think the definition isn't clear or helpful, that's a separate issue. But tying them together seems like it makes sense to me.

2021-05-25 16:24 UTC, nigelmegitt commented on spec/ttml2.xml
> +</note>
The conclusion I came to after the discussion was that this may be desirable in applications of TTML, but a) would be a normative change and b) is not necessarily desirable for every application.

2021-05-25 16:26 UTC, palemieux commented on spec/ttml2.xml
> +of the current <loc href="#terms-document-instance">document instance</loc> into an ordered sequence
Is t=0 always included in the _root temporal extent_?

2021-05-25 16:29 UTC, palemieux commented on spec/ttml2.xml
> +</note>
Stating that an ISD exists for every time t in [0, inf) does not compel an implementation to generate such an ISD, so there is no change in requirements, right?

2021-05-25 16:31 UTC, nigelmegitt commented on spec/ttml2.xml
> +of the current <loc href="#terms-document-instance">document instance</loc> into an ordered sequence
No, not necessarily. For example see https://www.w3.org/TR/2021/CR-ttml2-20210309/#semantics-media-document-timing

2021-05-25 16:34 UTC, nigelmegitt commented on spec/ttml2.xml
> +</note>
I believe it would compel in that way. The [[construct intermediate document]](https://www.w3.org/TR/2021/CR-ttml2-20210309/#procedure-construct-intermediate-document) procedure creates an ISD for every time interval obtained from [resolve timing]. 

If we were to make [resolve timing] generate a sequence that always begins with 0 and ends with infinity, then we would be requiring ISDs to be generated. That's a normative change, since right now TTML processors are _not_ required to do that.

2021-05-25 16:35 UTC, palemieux commented on spec/ttml2.xml
> +of the current <loc href="#terms-document-instance">document instance</loc> into an ordered sequence
The current text does not state that the time coordinates are limited to the _root temporal extent_. The proposed text introduces a new restriction, for which I do not see a clear motivation.

2021-05-25 16:38 UTC, nigelmegitt commented on spec/ttml2.xml
> +of the current <loc href="#terms-document-instance">document instance</loc> into an ordered sequence
What restriction is introduced? It seems to me that "active time duration" is genuinely synonymous with "root temporal extent" and therefore this is editorial. Also, the ability to allow the document processing context to affect the used values of the root temporal extent means that this adjusted wording remains very open for implementations to behave as they need to.

2021-05-25 16:38 UTC, palemieux commented on spec/ttml2.xml
> +</note>
> If we were to make [resolve timing] generate a sequence that always begins with 0 and ends with infinity, then we would be requiring ISDs to be generated. 

I propose not changing the algorithm, but merely stating that there is an ISD defined for every time t in [0, inf). Every application can choose what ISDs to generate, including none.

2021-05-25 16:50 UTC, nigelmegitt commented on spec/ttml2.xml
> +</note>
> Every application can choose what ISDs to generate, including none.

I think we're getting to the same endpoint but with different spec text changes. In effect, the edits I'm proposing already do state that.

2021-05-27 13:35 UTC, skynavga requested changes

2021-05-27 13:35 UTC, skynavga commented on spec/ttml2.xml
> +<p>divide the active time duration, i.e. the <loc href="#terms-root-temporal-extent">root temporal extent,</loc>
Please move the comma out of the new <loc>...</loc> element, i.e., put it immediately after the end tag.

2021-05-27 13:35 UTC, skynavga commented on spec/ttml2.xml
> +</note>
I'm reluctant to accept this elaboration since it may be viewed as defining implicit semantic constraint(s) that we have not completely fleshed out (or verified). I prefer removing this new text completely, and only making the first change shown above.

2021-05-27 16:02 UTC, nigelmegitt commented on spec/ttml2.xml
> +</note>
I thought we'd agreed all of these points, worded slightly differently, in the discussion of the issue #1232. However, there is certainly scope for revisiting the terminology we use in this area, e.g. is root temporal extent a duration or an interval, and what is it, and who gets to define it, and does a document get to define an interval at all, etc etc.

@palemieux and I discussed this during today's call, notes in https://github.com/w3c/ttml2/pull/1233#issuecomment-849751289

2021-05-27 16:03 UTC, nigelmegitt commented on spec/ttml2.xml
> +<p>divide the active time duration, i.e. the <loc href="#terms-root-temporal-extent">root temporal extent,</loc>
If there's consensus to make this change then I'll tweak that; since it seems there may not be, I'll leave it for the time being.

2021-05-27 22:32 UTC, skynavga commented on spec/ttml2.xml
> +</note>
I think we had conceptual agreement on these points. However, we did not discuss actually writing those points into the spec, and if we had discussed it, I would have opposed it for the reasons that both Pierre and I have raised. Namely, adding a clarification of this nature is potentially wrong and very risky IMO.

2021-06-12 16:45 UTC, skynavga commented on spec/ttml2.xml
> +<p>divide the active time duration, i.e. the <loc href="#terms-root-temporal-extent">root temporal extent,</loc>
Note that adding this parenthetical is semantically equivalent to the language found in §8.1.1:

>The root temporal extent, i.e., the time interval over which a document instance is active, ...

We SHOULD make this change (modulo fixing the comma placement).

2021-06-25 12:32 UTC, skynavga reviewed
Suggest changing to "may modify" or ", depending upon document processing context, may modify".

2021-06-25 12:34 UTC, skynavga commented on spec/ttml2.xml
> +<p>divide the active time duration, i.e. the <loc href="#terms-root-temporal-extent">root temporal extent,</loc>
Still need that comma moved.

2021-06-25 12:37 UTC, nigelmegitt commented on spec/ttml2.xml
> +<p>divide the active time duration, i.e. the <loc href="#terms-root-temporal-extent">root temporal extent,</loc>
Sorry, I don't see a comma that needs to be moved - can you point me at the one you mean @skynavga ?

2021-06-25 12:41 UTC, skynavga commented on spec/ttml2.xml
> +<p>divide the active time duration, i.e. the <loc href="#terms-root-temporal-extent">root temporal extent,</loc>
Change "extent,`</loc>`" to "extent`</loc>`,"

2021-06-25 12:44 UTC, nigelmegitt commented on spec/ttml2.xml
> +<p>divide the active time duration, i.e. the <loc href="#terms-root-temporal-extent">root temporal extent,</loc>
That isn't in the latest commit, I think?

2021-06-25 12:45 UTC, nigelmegitt commented on spec/ttml2.xml
> +<p>divide the active time duration, i.e. the <loc href="#terms-root-temporal-extent">root temporal extent,</loc>
Just confirmed, it was removed in 46e3bea.

2021-06-25 12:49 UTC, skynavga approved these changes
Thanks. LGTM.

2021-07-08 15:56 UTC, palemieux requested changes
The Root Temporal extent has a begin and end, in addition to a duration.

2021-07-08 15:56 UTC, palemieux commented on spec/ttml2.xml
> +is also the <loc href="#terms-root-temporal-extent">Root Temporal
```suggestion
is also the duration of the <loc href="#terms-root-temporal-extent">Root Temporal
```

2021-07-20 16:45 UTC, nigelmegitt commented on spec/ttml2.xml
> +is also the <loc href="#terms-root-temporal-extent">Root Temporal
I've reviewed the usage of Root Temporal Extent and agree that the way it is defined is as an interval that has both a duration and a begin time, so I'll update accordingly. There may be one or two inconsistencies elsewhere around this that need ironing out too.

2021-07-21 13:17 UTC, nigelmegitt commented on spec/ttml2.xml
> +is also the <loc href="#terms-root-temporal-extent">Root Temporal
Addressed in fc9c6ac - I looked for any other inconsistencies and did not find any other changes needed.

2021-07-21 22:36 UTC, palemieux approved these changes

2021-07-21 23:36 UTC, skynavga approved these changes

2021-07-21 23:37 UTC, merged