Metadata attributes apply as well as elements
w3c/ttml2 pull request #1273
Opened 2024-05-21 10:48 UTC by nigelmegitt

Closes #1271 by specifying that metadata attributes apply semantically as well as metadata elements, on those elements that accept metadata attributes.

In passing, also made a grammar fix where plurals "Any metadata" and "Any parameters" had singular "applies" form of the verb - replaced with plural "apply".

2024-06-06 23:01 UTC, skynavga requested changes

2024-06-06 23:01 UTC, skynavga commented on spec/ttml2.xml
> +element group or by <loc href="#attribute-vocab-group-metadata">Metadata attributes</loc>
Same comment as above.

2024-06-06 23:01 UTC, skynavga commented on spec/ttml2.xml
> +apply semantically to the <el>span</el> element and its descendants as a whole.</p>
Same comment as above.

2024-06-06 23:01 UTC, skynavga commented on spec/ttml2.xml
> +apply semantically to the <el>br</el> element and its descendants as a whole.</p>
Same comment as above.

2024-06-07 09:17 UTC, nigelmegitt commented on spec/ttml2.xml
> +element group or by <loc href="#attribute-vocab-group-metadata">Metadata attributes</loc>
Thanks for the review @skynavga - your proposal suggests that there is some lack of clarity now, which I will try to address.

However your specific proposal would not resolve the issue, since it's the metadata attributes on _this content element_ that the issue relates to, rather than the metadata attributes on child elements.

2024-06-07 09:41 UTC, nigelmegitt commented on spec/ttml2.xml
> +apply semantically to the <el>br</el> element and its descendants as a whole.</p>
Please see update in dedf3f9.

2024-06-07 09:41 UTC, nigelmegitt commented on spec/ttml2.xml
> +apply semantically to the <el>span</el> element and its descendants as a whole.</p>
Please see update in dedf3f9.

2024-06-07 09:41 UTC, nigelmegitt commented on spec/ttml2.xml
> +element group or by <loc href="#attribute-vocab-group-metadata">Metadata attributes</loc>
Please see update in dedf3f9.

2024-06-07 09:41 UTC, nigelmegitt commented on spec/ttml2.xml
> +element group or by <loc href="#attribute-vocab-group-metadata">Metadata attributes</loc>
Please see update in dedf3f9.

2024-06-07 09:43 UTC, nigelmegitt commented on spec/ttml2.xml
> +element group or by <loc href="#attribute-vocab-group-metadata">Metadata attributes</loc>
Please see update in dedf3f9. Wording switched to:

>Any metadata specified by Metadata attributes or by children in the Metadata.class element group apply semantically to ...

which hopefully clarifies that this is talking about metadata attributes on this element.

2024-06-08 02:25 UTC, skynavga approved these changes

2024-06-08 02:25 UTC, skynavga commented
LGTM

2024-06-09 13:49 UTC, nigelmegitt commented
@cconcolato do you want to review also, or shall I go ahead and merge this?

2024-06-11 23:26 UTC, cconcolato approved these changes

2024-06-12 07:50 UTC, merged